name: Auto Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  gh_pages:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: "Install Dependencies"
        run: yarn
      - name: "Get current date"
        run: echo "date=$(date --rfc-3339=date)" >> "$GITHUB_ENV"
      - name: "Build"
        run: yarn build
        env:
          REACT_APP_ROOM_ID: 1
          REACT_APP_BACKEND: "https://api.sbsybqlaaaaaaa.buzz/"
          REACT_APP_STORAGE: "https://file.sbsybqlaaaaaaa.buzz/"
          REACT_APP_BUILD_INFO: "v-${{ env.date }}"
      - name: "Deploy with gh-pages"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -u "github-actions-bot <support+actions@github.com>" -m "$COMMIT_MESSAGE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COMMIT_MESSAGE: "Build for [${{ github.event.head_commit.message }}]"
